import "./globals.css";
import { Inter } from "next/font/google";
import RQProviders from "@/utils/RQsetup/RQprovider";
import Navbar from "@/components/organisms/Navbar";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <RQProviders>
                    <Navbar />
                    {children}
                </RQProviders>
            </body>
        </html>
    );
}
