import "./globals.css";
import { Inter } from "next/font/google";
import RQProviders from "@/utils/RQsetup/RQprovider";
import Navbar from "@/components/organisms/Navbar";
import { Toaster } from "react-hot-toast";
import { Theme } from "@/utils/ThemeProvider/ThemeProvider";
import clsx from "clsx";
import Footer from "@/components/organisms/Footer";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={clsx(inter.className, "dark:bg-black bg-white")}>
                <RQProviders>
                    <Theme>
                        <Toaster position="top-right" reverseOrder={false} />
                        <Navbar />
                        {children}
                        <Footer />
                    </Theme>
                </RQProviders>
            </body>
        </html>
    );
}
